default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("POSTGRES_USERNAME") { 'dev' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'progshowzim' } %>

development:
  <<: *default
  database: ecommerce_development

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_production
